IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE [name] = 'VIEWNAMETAG') DROP VIEW VIEWNAMETAG
GO

CREATE VIEW VIEWNAMETAG
AS SELECT *
FROM OPENROWSET( 
       PROVIDER='CosmosDB',
       CONNECTION='Account=COSMOSACCOUNTNAMETAG;Database=DATABASENAMETAG',
       OBJECT='customers',
       SERVER_CREDENTIAL='CREDENTIALNAMETAG')
WITH (  
        ID	varchar(8000) '$.id',
        FirstName   varchar(1000) '$.firstName'
) AS docs
GO
