IF EXISTS (SELECT * FROM SYS.CREDENTIALS WHERE [name] = 'CREDENTIALNAME') DROP CREDENTIAL CREDENTIALNAME
CREATE CREDENTIAL CREDENTIALNAME
WITH IDENTITY = 'SHARED ACCESS SIGNATURE', SECRET = 'COSMOSACCOUNTKEY';

/*
Sql template for creating a credential. The tags CREDENTIALNAME,COMOSACCOUNTKEY should be replaced at runtime
*/



