apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    name: flaskapppod
    #We are targetting the containers in the specified pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
