jobs:
- job: Build
  steps:
  - script: |
      echo Hello world
      set
    displayName: Display all variables

  - task: UsePythonVersion@0
    displayName: 'Use Python $(PYTHONVERSION)'
    inputs:
      versionSpec: $(PYTHONVERSION)