trigger: 
  branches:
    include: [main,master]
  paths:
    include: [aks/800-devops-kubectl, aks/demo-flask-app, aks/demo-job]

pr:
  paths:
    include: [aks/800-devops-kubectl, aks/demo-flask-app, aks/demo-job]

variables:
- name: MajorVersion
  value: '1'
- name: MinorVersion
  value: '0'
- name: PatchNumber
  value: '1'
- name: PYTHONVERSION
  value: '3.9'
- name: BuildName
  ${{ if eq(variables['Build.SourceBranchName'],'main') }}:
    value: "${{ variables.MajorVersion}}.${{ variables.MinorVersion }}.${{ variables.PatchNumber }}.$(Build.BuildId)"
  ${{else}}:
    value: "${{ variables.MajorVersion}}.${{ variables.MinorVersion }}.${{ variables.PatchNumber }}-prerelease.$(Build.BuildId)"
- name: CONTAINERREGISTRY
  value: saupycontainerregistry001dev
- name: DemoJobDockerTagName
  value: "demojob:${{ variables.BuildName }}"
- name: WebAppDockerTagName
  value: "flaskwebapp:${{ variables.BuildName }}"
  #value: "saupycontainerregistry001dev.azurecr.io"

name: "${{ variables.BUILDNAME }}"

stages:
- stage: BUILD_STAGE
  displayName: Build stage
  pool: 
    name: Azure Pipelines
    vmImage: ubuntu-latest
  jobs:
    - template: ./build-template.yml
      parameters:
        azserviceconnection: 'azure pay as you go demo (sep 21)'

- stage: DEV_DEPLOY_STAGE
  displayName: Dev Deploy stage
  dependsOn: BUILD_STAGE
  variables: 
    environment: DEV
  pool: 
    name: Azure Pipelines
    vmImage: ubuntu-latest
  jobs:
    - template: ./deploy-template.yml
      parameters:
        azserviceconnection: 'azure pay as you go demo (sep 21)'
        aksresourcegroup: RG-AKS-DEMO-001
        aksresourcename: aks-viacli-$(environment)
        # reference a library variable here

- stage: PROD_DEPLOY
  dependsOn: DEV_DEPLOY_STAGE
  displayName: Prod Deploy stage
  variables:
    environment: PROD
    isMainBranch: $[eq(variables['Build.SourceBranchName'], 'refs/heads/main')]
  pool: 
    name: Azure Pipelines
    vmImage: ubuntu-latest
  condition: eq(variables.isMainBranch,true)
  jobs:
    - template: ./deploy-template.yml
      parameters:
        azserviceconnection: 'azure pay as you go demo (sep 21)'
        aksresourcegroup: RG-AKS-DEMO-001
        aksresourcename: aks-viacli-$(environment)
        # reference a library variable to get full independence from specifying the Azure resources within the YAML
