parameters:
  - name: environment
    type: string
  - name: azserviceconnection
    type: string
  - name: aksresourcegroup
    type: string
  - name: aksresourcename
    type: string
  - name: aksnamespace
    type: string

jobs:
- job: Deploy
  steps:
  - script: |
      echo Hello world in deploy template
      set
    displayName: Display all variables ${{ parameters.environment}}

  - task: KubectlInstaller@0
    displayName: 'Install Kubectl latest'

  - task: KubeloginInstaller@0
    displayName: 'Install Kubelogin latest'

  - task: HelmDeploy@1
    displayName: 'helm upgrade'
    inputs:
      azureSubscription: ${{ parameters.azserviceconnection }}
      azureResourceGroup: ${{ parameters.aksresourcegroup }}
      kubernetesCluster: ${{ parameters.aksresourcename }}
      namespace: ${{ parameters.aksnamespace}}
      command: upgrade
      chartType: FilePath
      chartPath: 'aks/800-devops-kubectl/helmcharts'
      releaseName: myaksdemo
      overrideValues: |
        demojobdockertagname=$(DemoJobDockerTagName)
        demowebappdockertagname=$(DemoWebAppDockerTagName)
        acr=$(CONTAINERREGISTRY)
        namespace=${{ parameters.aksnamespace}}
      arguments: '--create-namespace'