apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cron-job-memcachedwriter
spec:    
  schedule: "*/1 * * * *" #Job will run every 1 minutes
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: demo-cron-job
              image: saupycontainerregistry001dev.azurecr.io/demojob:v2
              imagePullPolicy: Always
              command: [ "python", "src/chron_memcachedwriter.py" ]
              env:
                - name: MEMCACHED_SERVER
                  value: "memcached-app-service.demoapp.svc.cluster.local"
